from __future__ import annotations

import argparse
import json
import logging
import shutil
import subprocess
import sys
from pathlib import Path

# Ensure project root is on sys.path for lib/ imports
_PROJECT_ROOT = str(Path(__file__).resolve().parent.parent.parent)
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

import lib.logger  # noqa: F401 — configures root logger
from datetime import datetime
from typing import Dict, List, Optional, Tuple

AUTHOR = "brynnnn12"
VERSION = "1.0"

BANNER = f"""
\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2557
\u2551                                                                      \u2551
\u2551   BBBB   RRRR   Y   Y  N   N  N   N  N   N  N   N                    \u2551
\u2551   B   B  R   R   Y Y   NN  N  NN  N  NN  N  NN  N                    \u2551
\u2551   BBBB   RRRR     Y    N N N  N N N  N N N  N N N                    \u2551
\u2551   B   B  R  R     Y    N  NN  N  NN  N  NN  N  NN                    \u2551
\u2551   BBBB   R   R    Y    N   N  N   N  N   N  N   N                    \u2551
\u2551                                                                      \u2551
\u2551   ScanForge v{{VERSION:<5}}  Automated nmap + nuclei scanner         \u2551
\u2551   {{AUTHOR}}                                                         \u2551
\u2551                                                                      \u2551
\u255a\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255d
"""

NMAP_PROFILES: Dict[str, List[str]] = {
    "quick":  ["-T4", "-F"],
    "basic":  ["-T4", "-sS", "-sV"],
    "full":   ["-T4", "-sS", "-sV", "-p-"],
    "service": ["-T4", "-sS", "-sV", "-sC"],
    "vuln":   ["-T4", "-sS", "-sV", "--script=vuln"],
}

NUCLEI_CATEGORIES: Dict[str, str] = {
    "all":          "",
    "cve":          "cves/",
    "exposures":    "exposures/",
    "misconfig":    "misconfiguration/",
    "vulnerabilities": "vulnerabilities/",
    "technologies": "technologies/",
    "default-login": "default-logins/",
    "fuzzing":      "fuzz/",
}

REPORT_HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ScanForge Report — {{ target }}</title>
<style>
body{font-family:monospace;max-width:1000px;margin:20px auto;padding:0 20px;background:#0d1117;color:#c9d1d9}
h1{color:#58a6ff;border-bottom:2px solid #30363d;padding-bottom:8px}
h2{color:#58a6ff;margin-top:24px}
table{width:100%;border-collapse:collapse;margin:12px 0}
th,td{text-align:left;padding:8px;border:1px solid #30363d}
th{background:#161b22;color:#8b949e}
tr:nth-child(even){background:#161b22}
.meta{color:#8b949e;font-size:14px}
.host{color:#7ee787;font-weight:bold}
.port{color:#79c0ff}
.service{color:#d2a8ff}
.vuln{color:#ff7b72}
.sep{background:#244;margin:0;padding:4px;text-align:center;color:#8b949e}
.footer{text-align:center;margin-top:32px;padding-top:16px;border-top:1px solid #30363d;color:#8b949e;font-size:13px}
</style>
</head>
<body>
<h1>ScanForge Report</h1>
<p class="meta">Target: {{ target }} | Date: {{ date }} | Author: {{ author }}</p>
{% if nmap_results %}
<h2>nmap Results</h2>
{% for host in nmap_results %}
<div class="host">{{ host.ip }} ({{ host.hostname or '—' }})</div>
<table><tr><th>Port</th><th>State</th><th>Service</th><th>Version</th></tr>
{% for p in host.ports %}
<tr><td class="port">{{ p.port }}/{{ p.protocol }}</td><td>{{ p.state }}</td><td class="service">{{ p.service }}</td><td>{{ p.version }}</td></tr>
{% endfor %}
</table>
{% endfor %}
{% endif %}
{% if nuclei_results %}
<h2>nuclei Results</h2>
<table><tr><th>Template</th><th>Severity</th><th>URL</th><th>Name</th></tr>
{% for n in nuclei_results %}
<tr><td>{{ n.template }}</td><td class="vuln">{{ n.severity }}</td><td>{{ n.url }}</td><td>{{ n.name }}</td></tr>
{% endfor %}
</table>
{% endif %}
<div class="footer">Generated by ScanForge v{{ version }} — {{ author }}</div>
</body>
</html>"""


def find_external(name: str) -> Optional[str]:
    return shutil.which(name)


def read_targets(path: Path) -> List[str]:
    if not path.exists():
        return []
    targets: List[str] = []
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            targets.append(line)
    return targets


def gather_targets(input_dir: Path, targets_file: Optional[Path]) -> List[str]:
    targets: List[str] = []
    if targets_file and targets_file.exists():
        targets.extend(read_targets(targets_file))
        return targets
    if not input_dir.exists():
        return targets
    for name in ["hosts.txt", "live.txt", "subdomains.txt"]:
        path = input_dir / name
        if path.exists():
            targets.extend(read_targets(path))
    return sorted(set(t.strip().lower() for t in targets if t.strip()))


def run_nmap(targets: List[str], profile: str, output_dir: Path) -> Tuple[int, Optional[Path]]:
    nmap = find_external("nmap")
    if not nmap:
        return 1, None
    targets_file = output_dir / "_nmap_targets.txt"
    targets_file.write_text("\n".join(targets), encoding="utf-8")
    xml_out = output_dir / "nmap_output.xml"
    flags = NMAP_PROFILES.get(profile, NMAP_PROFILES["basic"])
    cmd = [nmap, "-oX", str(xml_out)] + flags + ["-iL", str(targets_file)]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
    except FileNotFoundError:
        return 1, None
    if result.returncode != 0:
        return result.returncode, None
    return 0, xml_out if xml_out.exists() else None


def parse_nmap_xml(xml_path: Path) -> List[Dict]:
    import xml.etree.ElementTree as ET
    hosts: List[Dict] = []
    if not xml_path or not xml_path.exists():
        return hosts
    try:
        root = ET.parse(str(xml_path)).getroot()
    except ET.ParseError:
        return hosts
    for host in root.findall("host"):
        ip_el = host.find("address")
        if ip_el is None:
            continue
        ip = ip_el.get("addr", "")
        hostnames = host.find("hostnames")
        hostname = ""
        if hostnames is not None:
            hn = hostnames.find("hostname")
            if hn is not None:
                hostname = hn.get("name", "")
        ports: List[Dict] = []
        ports_el = host.find("ports")
        if ports_el is not None:
            for port in ports_el.findall("port"):
                port_id = port.get("portid", "")
                protocol = port.get("protocol", "")
                state_el = port.find("state")
                state = state_el.get("state", "") if state_el is not None else ""
                svc_el = port.find("service")
                svc = svc_el.get("name", "") if svc_el is not None else ""
                version = svc_el.get("product", "") if svc_el is not None else ""
                if svc_el is not None and svc_el.get("version"):
                    version = f"{version} {svc_el.get('version')}"
                ports.append({
                    "port": port_id, "protocol": protocol,
                    "state": state, "service": svc, "version": version.strip(),
                })
        hosts.append({"ip": ip, "hostname": hostname, "ports": ports})
    return hosts


def run_nuclei(targets: List[str], output_dir: Path, templates: str = "", templates_dir: str = "") -> Tuple[int, Optional[Path]]:
    nuclei = find_external("nuclei")
    if not nuclei:
        return 1, None
    json_out = output_dir / "nuclei_output.jsonl"
    cmd = [nuclei, "-jsonl", "-o", str(json_out)]
    cmd += ["-l", str(output_dir / "_nmap_targets.txt")]
    if templates:
        cmd += ["-t", templates]
    if templates_dir:
        cmd += ["-tp", templates_dir]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
    except FileNotFoundError:
        return 1, None
    if result.returncode not in (0, 1):
        return result.returncode, None
    return 0, json_out if json_out.exists() else None


def parse_nuclei_jsonl(jsonl_path: Path) -> List[Dict]:
    findings: List[Dict] = []
    if not jsonl_path or not jsonl_path.exists():
        return findings
    for line in jsonl_path.read_text(encoding="utf-8", errors="ignore").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        findings.append({
            "template": obj.get("template-id", ""),
            "name": obj.get("info", {}).get("name", ""),
            "severity": obj.get("info", {}).get("severity", ""),
            "url": obj.get("url", ""),
            "host": obj.get("host", ""),
            "matched": obj.get("matched-at", ""),
        })
    return findings


def generate_report(
    target: str,
    nmap_results: List[Dict],
    nuclei_results: List[Dict],
    output_dir: Path,
    write_json: bool = True,
    write_html: bool = True,
) -> None:
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    if write_json:
        report = {
            "target": target,
            "author": AUTHOR,
            "timestamp": timestamp,
            "nmap": {
                "hosts_scanned": len(nmap_results),
                "open_ports": sum(len(h["ports"]) for h in nmap_results),
                "hosts": nmap_results,
            },
            "nuclei": {
                "findings_count": len(nuclei_results),
                "findings": nuclei_results,
            },
        }
        (output_dir / "report.json").write_text(
            json.dumps(report, indent=2), encoding="utf-8"
        )
    if write_html:
        from string import Template
        t = Template(REPORT_HTML)
        html = t.safe_substitute(
            target=target,
            date=timestamp,
            author=AUTHOR,
            version=VERSION,
        )
        (output_dir / "report.html").write_text(html, encoding="utf-8")


def main() -> int:
    try:
        parser = argparse.ArgumentParser(
            prog="scanforge.py",
            description="Automated scanner wrapper \u2014 nmap + nuclei",
            epilog=(
                "Examples:\n"
                "  python scanforge.py -i recon/output/example.com\n"
                "  python scanforge.py -f targets.txt -p full\n"
                "  python scanforge.py -i ../reconforge/output/example.com --nmap-only\n"
                "  python scanforge.py -i ../reconforge/output/example.com --yes\n"
                "  python scanforge.py -i input --dry-run\n"
                "  # Interactive (default): prompts for nmap/nuclei choice\n\n"
                "Nmap profiles:\n"
                "  quick    -T4 -F (top ports)\n"
                "  basic    -T4 -sS -sV (SYN + version)\n"
                "  full     -T4 -sS -sV -p- (all ports)\n"
                "  service  -T4 -sS -sV -sC (default scripts)\n"
                "  vuln     -T4 -sS -sV --script=vuln (vuln scripts)\n\n"
                "Nuclei categories:\n"
                "  all             All templates\n"
                "  cve             CVEs\n"
                "  exposures       Exposures\n"
                "  misconfig       Misconfiguration\n"
                "  vulnerabilities  Vulnerabilities\n"
                "  technologies    Technology detection\n"
                "  default-login   Default logins\n"
                "  fuzzing         Fuzzing\n\n"
                "Use --nuclei-dir to point to custom templates path, e.g.\n"
                "  python scanforge.py -i input --nuclei-dir ~/nuclei-templates\n\n"
                "Author: brynnnn12  |  https://github.com/brynnnn12"
            ),
            formatter_class=argparse.RawDescriptionHelpFormatter,
        )
        parser.add_argument("-i", "--input", help="ReconForge output directory (reads hosts.txt, live.txt, subdomains.txt)")
        parser.add_argument("-f", "--file", help="Targets file (one per line, overrides -i)")
        parser.add_argument("-o", "--output", default="output", help="Output directory (default: output)")
        parser.add_argument("-p", "--profile", default="basic", choices=list(NMAP_PROFILES.keys()), help="nmap scan profile (default: basic)")
        parser.add_argument("--nmap-only", action="store_true", help="Run nmap only (no prompts)")
        parser.add_argument("--nuclei-only", action="store_true", help="Run nuclei only (no prompts)")
        parser.add_argument("--nuclei-category", default="all", choices=list(NUCLEI_CATEGORIES.keys()), help="nuclei template category (default: all)")
        parser.add_argument("--nuclei-dir", default="", help="Custom nuclei templates directory (e.g. ~/nuclei-templates)")
        parser.add_argument("--yes", action="store_true", help="Run all scanners (no prompts)")
        parser.add_argument("--dry-run", action="store_true", help="Show targets and config, don't scan")
        parser.add_argument("--no-json", action="store_true", help="Skip JSON report")
        parser.add_argument("--no-html", action="store_true", help="Skip HTML report")
        parser.add_argument("--version", action="version", version=f"ScanForge v{VERSION} \u2014 {AUTHOR}")
        args = parser.parse_args()

        if not args.input and not args.file:
            parser.print_help()
            return 1

        output_dir = Path(args.output).resolve()
        output_dir.mkdir(parents=True, exist_ok=True)

        input_dir = Path(args.input).resolve() if args.input else Path()
        targets_file = Path(args.file).resolve() if args.file else None
        targets = gather_targets(input_dir, targets_file)

        if not targets:
            print("[!] No targets found")
            return 1

        print(BANNER)
        print(f"  Output: {output_dir}")
        print(f"  Targets ({len(targets)}): {', '.join(targets[:10])}{' ...' if len(targets) > 10 else ''}")
        print(f"  Profile: {args.profile}")
        nmap_ok, nuclei_ok = find_external('nmap'), find_external('nuclei')
        print(f"  nmap:      {'[yes]' if nmap_ok else '[no] (not installed)'}")
        print(f"  nuclei:    {'[yes]' if nuclei_ok else '[no] (not installed)'}")
        print(f"  nuclei cat: {args.nuclei_category}")
        print(f"  nuclei dir: {args.nuclei_dir or '(nuclei default)'}")
        print()

        nmap_results: List[Dict] = []
        nuclei_results: List[Dict] = []
        run_nmap_flag = False
        run_nuclei_flag = False

        if args.nmap_only:
            run_nmap_flag = True
        elif args.nuclei_only:
            run_nuclei_flag = True
        elif args.yes:
            run_nmap_flag = True
            run_nuclei_flag = True
        else:
            p = input("  Run nmap? [Y/n]: ").strip().lower()
            if p in ("", "y", "yes"):
                run_nmap_flag = True
                prof = input(f"  nmap profile [{args.profile}]: ").strip()
                if prof in NMAP_PROFILES:
                    args.profile = prof
            p = input("  Run nuclei? [Y/n]: ").strip().lower()
            if p in ("", "y", "yes"):
                run_nuclei_flag = True
                cat_opts = ", ".join(NUCLEI_CATEGORIES.keys())
                cat = input(f"  nuclei category [all] ({cat_opts}): ").strip()
                if cat in NUCLEI_CATEGORIES:
                    args.nuclei_category = cat
                td = input("  Templates directory (enter for default): ").strip()
                if td:
                    args.nuclei_dir = td

        if args.dry_run:
            will = []
            if run_nmap_flag: will.append("nmap")
            if run_nuclei_flag:
                label = f"nuclei ({args.nuclei_category})"
                if args.nuclei_dir:
                    label += f" dir={args.nuclei_dir}"
                will.append(label)
            print(f"  Will run: {', '.join(will) if will else '(none)'}")
            print("  [DRY-RUN] Targets ready \u2014 no scan performed\n")
            return 0

        if run_nmap_flag:
            nmap_bin = find_external("nmap")
            if nmap_bin:
                print(f"\n  \u2500\u2500 Running nmap ({args.profile}) \u2500\u2500")
                rc, xml_path = run_nmap(targets, args.profile, output_dir)
                if rc == 0 and xml_path:
                    nmap_results = parse_nmap_xml(xml_path)
                    ports = sum(len(h["ports"]) for h in nmap_results)
                    print(f"    nmap done: {len(nmap_results)} hosts, {ports} open ports\n")
                else:
                    print(f"    [!] nmap failed (exit {rc})\n")
            else:
                print("  [!] nmap not found \u2014 skipping\n")

        if run_nuclei_flag:
            nuclei_bin = find_external("nuclei")
            if nuclei_bin:
                cat_label = args.nuclei_category
                cat_path = NUCLEI_CATEGORIES.get(cat_label, "")
                print(f"  \u2500\u2500 Running nuclei ({cat_label}) \u2500\u2500")
                rc, jsonl_path = run_nuclei(targets, output_dir, templates=cat_path, templates_dir=args.nuclei_dir)
                if rc == 0 and jsonl_path:
                    nuclei_results = parse_nuclei_jsonl(jsonl_path)
                    print(f"    nuclei done: {len(nuclei_results)} findings\n")
                else:
                    print(f"    [!] nuclei failed or no results\n")
            else:
                print("  [!] nuclei not found \u2014 skipping\n")

        generate_report(
            target=input_dir.name or Path(args.file or "unknown").stem,
            nmap_results=nmap_results,
            nuclei_results=nuclei_results,
            output_dir=output_dir,
            write_json=not args.no_json,
            write_html=not args.no_html,
        )

        print(f"  \u2500\u2500 Done \u2500\u2500")
        print(f"  Reports: {output_dir}")
        return 0
    except (KeyboardInterrupt, EOFError):
        print("\n  [!] Interrupted")
        return 130
    except Exception as exc:
        logging.exception("ScanForge failed")
        print(f"\n  [red]Error:[/red] {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
