from __future__ import annotations

from pathlib import Path
from typing import Dict, List

from core.utils import ensure_dir, now_timestamp, write_json, write_text

AUTHOR = "brynnnn12"

HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ReconForge Report &mdash; {domain}</title>
<style>
* {{ margin:0; padding:0; box-sizing:border-box; }}
body {{ font-family:"JetBrains Mono","Cascadia Code","Fira Code",monospace; background:#0d1117; color:#c9d1d9; padding:2rem; max-width:1000px; margin:auto; }}
h1 {{ color:#58a6ff; border-bottom:2px solid #21262d; padding-bottom:.5rem; margin-bottom:1.5rem; }}
h2 {{ color:#f0883e; margin-top:1.5rem; margin-bottom:.5rem; }}
h3 {{ color:#8b949e; margin-top:1rem; margin-bottom:.5rem; }}
table {{ border-collapse:collapse; width:100%; margin-bottom:1rem; }}
th,td {{ padding:.5rem .75rem; text-align:left; border:1px solid #30363d; }}
th {{ background:#21262d; color:#58a6ff; font-weight:600; }}
tr:nth-child(even) {{ background:#161b22; }}
.summary td:last-child {{ text-align:right; font-weight:bold; }}
.meta {{ color:#8b949e; margin-bottom:1.5rem; }}
ul {{ list-style:none; }}
li {{ padding:.25rem 0; }}
a {{ color:#58a6ff; text-decoration:none; }}
a:hover {{ text-decoration:underline; }}
.footer {{ margin-top:2rem; padding-top:1rem; border-top:1px solid #21262d; color:#484f58; font-size:.85rem; }}
</style>
</head>
<body>
<h1>ReconForge Report &mdash; {domain}</h1>
<p class="meta">by brynnnn12 | {timestamp} | Total Assets: {total_assets}</p>

<h2>Summary</h2>
<table class="summary">
<tr><th>Module</th><th>Count</th></tr>
{summary_rows}
</table>

<h2>Results</h2>
{module_sections}

<p class="footer">Generated by ReconForge v0.2.0 by brynnnn12</p>
</body>
</html>"""


class ReportModule:
    name = "report"

    def __init__(self, domain: str, output_dir: Path) -> None:
        self.domain = domain
        self.output_dir = output_dir

    def write(
        self,
        results: Dict[str, List[str]],
        summary: Dict[str, int],
        json_enabled: bool,
        html_enabled: bool = False,
    ) -> None:
        ensure_dir(self.output_dir)
        timestamp = now_timestamp()
        total_items = sum(summary.values())

        self._write_txt(summary, timestamp, total_items)
        if json_enabled:
            self._write_json(summary, timestamp, total_items)
        if html_enabled:
            self._write_html(results, summary, timestamp, total_items)

    def _write_txt(self, summary: Dict[str, int], timestamp: str, total_items: int) -> None:
        lines = [
            "ReconForge Report",
            f"Author: {AUTHOR}",
            f"Timestamp: {timestamp}",
            f"Domain: {self.domain}",
            f"Total Assets: {total_items}",
            "",
            "Module Summary:",
        ]
        for name, count in summary.items():
            lines.append(f"- {name}: {count}")
        write_text(self.output_dir / "report.txt", "\n".join(lines) + "\n")

    def _write_json(self, summary: Dict[str, int], timestamp: str, total_items: int) -> None:
        write_json(self.output_dir / "report.json", {
            "tool": "ReconForge",
            "author": AUTHOR,
            "version": "0.2.0",
            "timestamp": timestamp,
            "domain": self.domain,
            "total_assets": total_items,
            "summary": summary,
        })

    def _write_html(
        self,
        results: Dict[str, List[str]],
        summary: Dict[str, int],
        timestamp: str,
        total_items: int,
    ) -> None:
        summary_rows = "\n".join(
            f"<tr><td>{name}</td><td>{count}</td></tr>"
            for name, count in summary.items()
        )

        module_sections = ""
        for name, items in results.items():
            section = f"<h3>{name} ({len(items)} items)</h3>\n<ul>\n"
            for item in items[:100]:
                safe = item.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                if item.startswith("http"):
                    section += f'<li><a href="{safe}" target="_blank" rel="noopener">{safe}</a></li>\n'
                else:
                    section += f"<li>{safe}</li>\n"
            if len(items) > 100:
                section += f"<li><em>... and {len(items) - 100} more</em></li>\n"
            section += "</ul>\n"
            module_sections += section

        html = HTML_TEMPLATE.format(
            domain=self.domain,
            timestamp=timestamp,
            total_assets=total_items,
            summary_rows=summary_rows,
            module_sections=module_sections,
        )
        write_text(self.output_dir / "report.html", html)
